import { Inter } from "next/font/google";
import "../../public/css/globals.css";
import "../../public/css/style.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const user = {
    username:"sarc@gmail.com",
    position:"Gerente",
    permission:"all"
}

  return (
    <html lang="en">
      <body className={inter.className} user={user}>
        {children}
      </body>
    </html>
  );
}
